Feature/tasks on main page
g-palanskiy/FinalFront_PalanskiyGA pull request #1
Opened 2023-01-27 13:44 UTC by g-palanskiy

Created a main page and rendered news from the database on it

2023-01-27 13:57 UTC, D-pavlo-v requested changes
check comments

2023-01-27 13:57 UTC, D-pavlo-v commented on .env
> +REACT_APP_API_URL = "http://localhost:8000/api"
в гитигнор! в енв нужно писать окружение, а не ури апи. а ури апи лучше прописывать в папке constants, и в зависимости от окружения менять его

2023-01-27 13:57 UTC, D-pavlo-v commented on src/pages/MainPage.jsx
> +  }, [dispatch]);
за диспатчем можно не следить

2023-01-27 13:57 UTC, D-pavlo-v commented on src/components/NewsList/NewsList.jsx
> +  news: PropTypes.arrayOf(PropTypes.shape({})).isRequired,
шейп хорошо бы расписать

2023-01-27 13:57 UTC, D-pavlo-v commented on src/components/NewsCard/NewsCard.jsx
> +
можно не отделять энтером, но если так нравится, то оставь

2023-01-27 14:13 UTC, g-palanskiy commented on src/pages/MainPage.jsx
> +  }, [dispatch]);
Это для Eslint

2023-01-27 14:13 UTC, g-palanskiy commented on src/components/NewsCard/NewsCard.jsx
> +
Это прописано в требованиях

2023-01-27 14:24 UTC, ekaterinagaltsova commented on src/pages/MainPage.jsx
> +    : <CustomAlert error={error} />;
сделай компонент универсальным - и для вывода инфы, и для вывода ошибок

2023-01-27 14:25 UTC, ekaterinagaltsova commented on src/redux/sagas/newsSaga.js
>      yield put(newsReceived(news.data));
деструктурируй data

2023-01-27 14:46 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +      <h1 className="site-name">News</h1>
есть класс - нет стилей для него

2023-01-30 07:09 UTC, ekaterinagaltsova commented on src/components/CustomAlert/CustomAlert.jsx
> +      <AlertTitle>Error</AlertTitle>
title !== Error

2023-01-30 07:10 UTC, ekaterinagaltsova commented on src/components/CustomAlert/CustomAlert.jsx
>  export default CustomAlert;
все компоненты, у которых есть родитель, оберни в memo

2023-01-30 07:19 UTC, ekaterinagaltsova commented on src/components/news-card/NewsCard.jsx
>  import { CardActionArea } from '@mui/material';
сохраняй единообразие импортов
import CardActionArea from '@mui/material/CardActionArea';

2023-01-30 09:09 UTC, ekaterinagaltsova approved these changes

2023-02-06 14:49 UTC, merged