Feature/authorization
g-palanskiy/FinalFront_PalanskiyGA pull request #2
Opened 2023-02-09 14:19 UTC by g-palanskiy

2023-02-09 14:31 UTC, ekaterinagaltsova commented on src/redux/sagas/logoutSaga.js
> +    yield put(authSucceed([]));
юзер как массив?)
вот тут лучше экшен логаута  - обнулить юзера и тп

2023-02-09 14:43 UTC, ekaterinagaltsova commented on src/redux/sagas/authSaga.js
>      const response = yield call(api.post, path, body);
деструктурни токен и юзера

2023-02-09 14:44 UTC, ekaterinagaltsova commented on src/redux/sagas/authSaga.js
>      if (response) {
if (response) {
сомневаешься в респонсе?

2023-02-09 14:47 UTC, ekaterinagaltsova commented on src/redux/sagas/authSaga.js
>    } catch (error) {
try {
} catch (e) {
}
format accordingly

2023-02-09 14:50 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +  const username = useSelector((state) => state.auth.authUser.name);
селекторы выше хуков

2023-02-09 14:51 UTC, ekaterinagaltsova commented on src/components/LogoutForm/LogoutForm.jsx
> +        <LoadingButton
промаппить кнопошки

2023-02-09 14:53 UTC, ekaterinagaltsova commented on src/redux/reducers/authReducer.js
> +  authUser: [],
разве юзер не объект?

2023-02-09 14:53 UTC, ekaterinagaltsova commented on src/redux/sagas/verifySaga.js
> +    const response = yield call(api.get, 'auth');
деструктуризация!

2023-02-09 14:54 UTC, ekaterinagaltsova commented on src/redux/sagas/verifySaga.js
> +    const response = yield call(api.get, 'auth');
что есть  'auth'?

2023-02-09 14:56 UTC, ekaterinagaltsova commented on src/components/AuthForm/AuthForm.jsx
>  function AuthForm({ formType }) {
а у родителя это пропс обернут в мемо? может лучше подтянуть его из стора?

2023-02-10 07:24 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +  const username = useSelector((state) => state.auth.user.name);
а если у юзера нет имени рухнет вся логика отображения

2023-02-10 07:26 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +              Sign Up
все неизменные текстовки в хардкордные константы

2023-02-10 07:28 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +            <Avatar>{username[0].toUpperCase()}</Avatar>
можно попробовать изменить первую букву с помощью  css

2023-02-10 07:32 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +          <div className="account">
очень нужна лишняя обертка? нельзя стили на саму кнопку переложить?

2023-02-10 07:33 UTC, ekaterinagaltsova commented on src/components/Header/Header.jsx
> +        : (
замени тернарник на два условных рендеринга

2023-02-10 07:33 UTC, ekaterinagaltsova commented on src/redux/actions/auth.js
> +export const authRequest = (body) => ({
payload

2023-02-10 07:35 UTC, ekaterinagaltsova commented on src/redux/sagas/authSaga.js
> +    const path = (yield select((state) => state.modal.modalType)) === 'Sign Up'
вынеси в константу yield select((state) => state.modal.modalType)

2023-02-10 07:42 UTC, ekaterinagaltsova commented on src/components/AuthForm/AuthForm.jsx
> +                {errors[name] && touched[name] ? (
замени на условный рендеринг

2023-02-10 11:22 UTC, ekaterinagaltsova commented on src/components/AuthForm/constants.js
> +export const logInFields = [
похоже на дублирование кода

2023-02-10 12:33 UTC, D-pavlo-v requested changes
Check comments

2023-02-10 12:33 UTC, D-pavlo-v commented on src/components/AuthForm/AuthForm.jsx
> +          {error && errorMessages.map((item) => <CustomAlert key={item} message={item} severity="error" />)}
могут быть проблемы с реактивностью из-за того, что это не состояние

2023-02-10 12:33 UTC, D-pavlo-v commented on src/components/AuthForm/AuthForm.jsx
> +  const fieldTypes = modalType === LOG_IN
сомнительное решение. А если еще новые формы появятся, то еще тернарник добавлять будешь? лучше написать функцию, которая будет принимать тип и возвращать то что нужно

2023-02-10 12:33 UTC, D-pavlo-v commented on src/components/Header/Header.jsx
> +import React, { memo, useEffect } from 'react';
а что мемоизируем?

2023-02-10 12:33 UTC, D-pavlo-v commented on src/components/CustomModal/CustomModal.jsx
> +        {modalType === 'Logout'
аналогично аусФорм

2023-02-10 12:33 UTC, D-pavlo-v commented on src/components/Header/Header.jsx
> +    if (localStorage.getItem('token')) dispatch(verifyRequest());
вот это хорошо сделал 👍

2023-02-10 13:04 UTC, g-palanskiy commented on src/components/Header/Header.jsx
> +import React, { memo, useEffect } from 'react';
export default memo(Header);

2023-02-13 07:00 UTC, D-pavlo-v requested changes
check comments

2023-02-13 07:00 UTC, D-pavlo-v commented on src/components/CustomModal/CustomModal.jsx
> +          position: 'absolute',
это можно вынести в styles.js

2023-02-13 07:43 UTC, D-pavlo-v approved these changes

2023-02-13 07:44 UTC, merged